services:
  - type: web
    name: pdf-page-mixer-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    port: 8080
    envVars:
      - key: app.frontend-origin
        sync: false
